name: build
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v2-beta
        with:
          go-version: 1.13
        id: go

      - uses: actions/checkout@v2

      - name: Build
        run: go install .