on:
    push:
      branches:
        - master
  
  jobs:
    publish:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-go@master
            with:
                go-version: 1.14
            id: go
        - name: Build Image
          env:
            DockerUsername: ${{ secrets.DockerUsername }}
            DockerPassword: ${{ secrets.DockerPassword }}
          run: |
            docker login -u $DockerUsername -p $DockerPassword
            docker build -t yisar/clicli_server .
            docker push yisar/clicli_server
    # deploy:
    #   runs-on: ubuntu-latest
    #   needs: [publish]
    #   steps:
    #     - uses: appleboy/ssh-action@master
    #       with:
    #         host: ${{ secrets.DEPLOY_HOST }}
    #         username: ${{ secrets.DEPLOY_USERNAME }}
    #         password: ${{ secrets.DEPLOY_PASSWORD }}
    #         port: 22
    #         script: ${{ secrets.DeployScript }}